### PR TITLE
Addition of June 2019 Print and Play

### PR DESCRIPTION
**Pull request by XoeAllred**
Update to the Exiles and Partisans cards.
Update to the Underground Duchy.
Update to the Corvid Conspiracy.
Added Official Bot Print and Play boards.
Addition of a Rootbotics (Official Bots) tab to faction selection board.
Changed faction selection board tab buttons to account for tighter space.
Changed Underground Duchy faction button (Removed "The Great" to match board changes)
Changed Weekly Croak faction button (Added character art  :3 )
Updated the Weekly Croak fan faction.
Updated the Boarish Hoards fan faction.

### CODE REVIEW

**Comment by Eldinnie** [comment]
First of all. Great work! Thanks!
Some things that would be great if you can change.
small stuff:
- make the weekly croak meeples double sided. (Like i did with all the others) so they look good from any angle
- Make the winter priority tile for the bots a tile (instead of a token) to account for the underside.
- In law of bots it shows the one with the river for the vagabond and the identical other one for all other factions. In the mod it also shows the river one for the cats
Slightly more stuff:
- right now when you select an official bot it loads the law of better bot and some extra dominance and spy cards. When selecting an official bot this should probably be the official law of bot.

Do you still have some time to address these? If not I'll merge and fix them myself.

Thanks again!

**Comment by XoeAllred** [comment]
I won't have time to fix this weekend, but I can work on it next week!

**Comment by XoeAllred** [comment]
Remaining Issues:

- Winter priority tiles are still tiles.
- Fan bot law unchanged.
- Fan bot law still loads instead of the official bot law.
- Ruins aren't given items when the Boars are selected without a vagabond.
- Missing Adventurer and Harrier Vagabonds.

I won't be able to get to these until later in the week, but if anyone has time to address, feel free!

**Comment by XoeAllred** [comment]
This latest update adds the following adjustments:

- Relationship markers for vagabonds updated to latest pnp ones for duchy and corvids.
- Fangus Khan relationship marker moved from vagabonds' boards to Fangus Khan board.
- First fan bot selected spawns spy cards and better bot project law, while first official bot selected just spawns the rootbotics law doc.  (Current issue, if you spawn one of each, only the law for the first will spawn, not sure if we need to do anything about this.)
- If the Boars are selected, but no vagabond, items will still be placed under the ruins.

Still needs to be done:
- Planning to add autumn priority map to other side of winter priority map token.
- Addition of Adventurer and Harrier Vagabonds
- Update to Raft piece
- Addition of Mountain pass tower.
- Update to Lake Map rules to include bit about getting an extra card.

**Comment by XoeAllred** [comment]
Okay, I'm done working on this, unless you'd like me to work on adding the two new vagabonds, but it looks like @McChew may already be working on that.  Let me know if you see any other issues!

Things that are missing that I am not planning on adding:

- Addition of Adventurer and Harrier Vagabonds
- Update to Raft Piece
- Addition of Mountain pass tower.
- Mountain map with default clearing markers.

**Comment by XoeAllred** [comment]
Actually, hold on, I appear to have broken something with the robot raccoon.

**Comment by XoeAllred** [comment]
Okay, I've fixed it, should be ready now.

**Pull request merged**
